import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useQuery, useMutation, useQueryClient } from 'react-query';

const Home: NextPage = (props) => {
  console.log(props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>{'Welcome to my world'}</div>
      <div>{props.data.title}</div>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://hacker-news.firebaseio.com/v0/item/8863.json?print=pretty`,
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
